// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: resume-service.proto

package resume

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResumeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResumeUuid []byte `protobuf:"bytes,1,opt,name=resume_uuid,json=resumeUuid,proto3" json:"resume_uuid,omitempty"`
}

func (x *ResumeReq) Reset() {
	*x = ResumeReq{}
	mi := &file_resume_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeReq) ProtoMessage() {}

func (x *ResumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_resume_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeReq.ProtoReflect.Descriptor instead.
func (*ResumeReq) Descriptor() ([]byte, []int) {
	return file_resume_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResumeReq) GetResumeUuid() []byte {
	if x != nil {
		return x.ResumeUuid
	}
	return nil
}

type ResumeDbEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResumeDbEmpty) Reset() {
	*x = ResumeDbEmpty{}
	mi := &file_resume_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDbEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDbEmpty) ProtoMessage() {}

func (x *ResumeDbEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_resume_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDbEmpty.ProtoReflect.Descriptor instead.
func (*ResumeDbEmpty) Descriptor() ([]byte, []int) {
	return file_resume_service_proto_rawDescGZIP(), []int{1}
}

var File_resume_service_proto protoreflect.FileDescriptor

var file_resume_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x13, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x55, 0x75,
	0x69, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x62, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x32, 0xb5, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x1a, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x62, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x35, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x62, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x42, 0x79, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resume_service_proto_rawDescOnce sync.Once
	file_resume_service_proto_rawDescData = file_resume_service_proto_rawDesc
)

func file_resume_service_proto_rawDescGZIP() []byte {
	file_resume_service_proto_rawDescOnce.Do(func() {
		file_resume_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_resume_service_proto_rawDescData)
	})
	return file_resume_service_proto_rawDescData
}

var file_resume_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resume_service_proto_goTypes = []any{
	(*ResumeReq)(nil),     // 0: service.ResumeReq
	(*ResumeDbEmpty)(nil), // 1: service.ResumeDbEmpty
	(*Resume)(nil),        // 2: models.Resume
	(*Resumes)(nil),       // 3: models.Resumes
}
var file_resume_service_proto_depIdxs = []int32{
	2, // 0: service.ResumeService.CreateResume:input_type -> models.Resume
	1, // 1: service.ResumeService.GetResumes:input_type -> service.ResumeDbEmpty
	0, // 2: service.ResumeService.GetResumeByUUID:input_type -> service.ResumeReq
	1, // 3: service.ResumeService.CreateResume:output_type -> service.ResumeDbEmpty
	3, // 4: service.ResumeService.GetResumes:output_type -> models.Resumes
	2, // 5: service.ResumeService.GetResumeByUUID:output_type -> models.Resume
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resume_service_proto_init() }
func file_resume_service_proto_init() {
	if File_resume_service_proto != nil {
		return
	}
	file_resume_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resume_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resume_service_proto_goTypes,
		DependencyIndexes: file_resume_service_proto_depIdxs,
		MessageInfos:      file_resume_service_proto_msgTypes,
	}.Build()
	File_resume_service_proto = out.File
	file_resume_service_proto_rawDesc = nil
	file_resume_service_proto_goTypes = nil
	file_resume_service_proto_depIdxs = nil
}
